### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by chrisl-peopleplus** [RusticiSoftware/scormcloud-api-v2-client-javascript#12]
Is there any plan to make typescript definitions for the library? I might see if I can  do it but I'm no Typescript expert by any means

**Comment by mjschuetze102** [comment]
This library is generated based off of our API, which conforms to the OpenAPI spec (v2.0), using [swagger-codegen](https://github.com/swagger-api/swagger-codegen). If you would like a typescript version swagger-codegen does provide several libraries that could meet your needs:

<img width="195" alt="image" src="https://user-images.githubusercontent.com/16418232/204313742-2b58a684-07bd-419c-bb35-472ab08908ff.png">

We currently do not have plans to support a typescript version of the library, but generating your own should be as easy as the following:

```
git clone https://github.com/swagger-api/swagger-codegen
cd swagger-codegen
mvn clean package
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
   -i https://app.cloud.scorm.com/sc/swagger/swagger.json \
   -l language_you_wish_to_use \
   -o /path/to/save/typescript_api_client
```

Everything you need to get started working with SCORM Cloud will be produced in a library which would look similar to this one.

---

We maintain client libraries for six languages and every once in a while we will find something that one of them supports that another one doesn't. It doesn't hinder the use of the library at all, but for the ones we maintain, we want them to look and act as similarly as possible while understanding language constraints. As such it is unlikely that we would add in another language that we would need to support.

**Comment by mjschuetze102** [comment]
I'm going to go ahead and close this. Let me know if there is anything else I can help with
